// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AjaxController from "./ajax_controller"
application.register("ajax", AjaxController)

import BarChartDashboardController from "./bar_chart_dashboard_controller"
application.register("bar-chart-dashboard", BarChartDashboardController)

import BarChartsController from "./bar_charts_controller"
application.register("bar-charts", BarChartsController)

import DoughnutController from "./doughnut_controller"
application.register("doughnut", DoughnutController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MultiBarChartDashboardController from "./multi_bar_chart_dashboard_controller"
application.register("multi-bar-chart-dashboard", MultiBarChartDashboardController)

import PieChartsController from "./pie_charts_controller"
application.register("pie-charts", PieChartsController)

import RangeMarkersController from "./range_markers_controller"
application.register("range-markers", RangeMarkersController)
