// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BarChartDashboardController from "./bar_chart_dashboard_controller"
application.register("bar-chart-dashboard", BarChartDashboardController)

import BarChartsController from "./bar_charts_controller"
application.register("bar-charts", BarChartsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PieChartsController from "./pie_charts_controller"
application.register("pie-charts", PieChartsController)
